### ISSUE TITLE
Two shoutboxes 

### ISSUE THREAD

**Issue by danger89** [Schamper/nodebb-plugin-shoutbox#91]
Hi,

When I press on the title, a link will open to the shoutbox (let's call it fullscreen mode).

But on that moment I see 2 shout-boxes!? Where the bottom one can't be used:
Example:
https://forum.libreweb.org/shoutbox

This looks like a bug. I also have an attachment:
![2_boxes](https://cloud.githubusercontent.com/assets/628926/11538962/d7e1ac72-9924-11e5-9219-708790ca1ad3.png)

Ps.
The shoutbox below doesn't work.

Kind regards,
Melroy van den Berg

**Comment by Benderwan** [comment]
This has to do with #85

**Comment by danger89** [comment]
I see, still @Schamper closed your issue, but it's actually not a good solution. Most of the people will use the widget feature, this should be a setting or something...

Don't just close this issue.

**Comment by Schamper** [comment]
I closed it because it's not an issue with the shoutbox. The shoutbox is a widget, *you* decided to put that widget in a *global* widget area. You know what a global widget area is? It's a widget area on **every** page. I can't change that. The only way to change that is to use a theme with a non-global widget area and put the shoutbox in there. Alternatively you can use a custom theme that overrides the dedicated shoutbox page with an empty page and keep the widget in the global area.

**Comment by danger89** [comment]
Well, you can atleast check if the url is equal to 'shoutbox' and at that moment block hide 1 shoutbox. This could be a setting.

**Comment by Schamper** [comment]
I'm not a themer but you should be able to get enough information from [here](https://community.nodebb.org/topic/474/how-to-making-a-custom-nodebb-theme/3) and [here](https://github.com/NodeBB/nodebb-theme-quickstart).

I've added your suggestion (https://github.com/Schamper/nodebb-plugin-shoutbox/commit/7e6034932541d4d291cbb011639d94f2f67b1e6a). Reason why I didn't want to do this in the first place is because I thought I wouldn't have access to that data in that method but it turns out I did. I won't publish a new version to npm yet until I fix some of the other issues though.
